version: '3'

services:

  msa:
    image: nexus3.onap.org:10003/onap/tapisimulator
    restart: always
    environment:
      Controller: MSA
    ports:
      - "8082:8082"

  tap1:
    image: nexus3.onap.org:10003/onap/tapisimulator
    restart: always
    ports:
    - 8081:8080
    environment:
      Controller: TAPI1

  tapi2:
    image: nexus3.onap.org:10003/onap/tapisimulator
    ports:
      - "8083:8080"
    restart: on-failure
